version: "3"
services:
  postgres:
    container_name: student_class_pg
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: development
      POSTGRES_DB: student_class
      PGDATA: /var/lib/postgres